//
//  DeveloperPreview.swift
//  OYO-IOS
//
//  Created by jatin foujdar on 23/05/25.
//

import Foundation

class DeveloperPreview {
    static let shared = DeveloperPreview()
    
    var listings: [ListingModel] = [
        .init(
            id: UUID().uuidString,
            ownerUId: UUID().uuidString,
            ownerName: "Aarav Sharma",
            onwerImageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
            numberOfBedrooms: 2,
            numberOfBathroom: 2,
            numberOfGuests: 4,
            numberOfBeds: 2,
            pricePerNight: 3200,
            latitude: 28.6139,
            longitude: 77.2090,
            address: "123 Connaught Place",
            city: "New Delhi",
            state: "Delhi",
            title: "Raj Mahal",
            rating: 4.8,
            feature: [.selfCheckIn, .superHost],
            amenities: [.wifi, .kitchen, .tv, .laundry, .balcony],
            type: .apartment
        ),
        .init(
            id: UUID().uuidString,
            ownerUId: UUID().uuidString,
            ownerName: "Meera Joshi",
            onwerImageUrl: "https://images.unsplash.com/photo-1597003754034-a0b7f27e8f1b?auto=format&fit=crop&w=800&q=80",
            numberOfBedrooms: 3,
            numberOfBathroom: 2,
            numberOfGuests: 6,
            numberOfBeds: 3,
            pricePerNight: 4500,
            latitude: 19.0760,
            longitude: 72.8777,
            address: "45 Marine Drive",
            city: "Mumbai",
            state: "Maharashtra",
            title: "Sea Breeze Villa",
            rating: 4.9,
            feature: [.superHost],
            amenities: [.wifi, .tv,   .balcony],
            type: .villa
        ),
        .init(
            id: UUID().uuidString,
            ownerUId: UUID().uuidString,
            ownerName: "Ravi Verma",
            onwerImageUrl: "https://images.unsplash.com/photo-1600585153837-200f3d3d4edc?auto=format&fit=crop&w=800&q=80",
            numberOfBedrooms: 1,
            numberOfBathroom: 1,
            numberOfGuests: 2,
            numberOfBeds: 1,
            pricePerNight: 1800,
            latitude: 12.9716,
            longitude: 77.5946,
            address: "22 MG Road",
            city: "Bengaluru",
            state: "Karnataka",
            title: "Tech City Studio",
            rating: 4.5,
            feature: [],
            amenities: [.wifi, .kitchen, .tv],
            type: .apartment
        ),
        .init(
            id: UUID().uuidString,
            ownerUId: UUID().uuidString,
            ownerName: "Priya Reddy",
            onwerImageUrl: "https://images.unsplash.com/photo-1599423300746-b62533397364?auto=format&fit=crop&w=800&q=80",
            numberOfBedrooms: 2,
            numberOfBathroom: 1,
            numberOfGuests: 3,
            numberOfBeds: 2,
            pricePerNight: 2500,
            latitude: 17.3850,
            longitude: 78.4867,
            address: "Hill View Residency",
            city: "Hyderabad",
            state: "Telangana",
            title: "Charminar View Flat",
            rating: 4.3,
            feature: [],
            amenities: [.wifi, .tv, .laundry],
            type: .apartment
        ),
        .init(
            id: UUID().uuidString,
            ownerUId: UUID().uuidString,
            ownerName: "Vikram Kapoor",
            onwerImageUrl: "https://images.unsplash.com/photo-1600585153843-1f1b60d5c6d4?auto=format&fit=crop&w=800&q=80",
            numberOfBedrooms: 4,
            numberOfBathroom: 3,
            numberOfGuests: 8,
            numberOfBeds: 4,
            pricePerNight: 6000,
            latitude: 26.9124,
            longitude: 75.7873,
            address: "Raja Park",
            city: "Jaipur",
            state: "Rajasthan",
            title: "Heritage Haveli",
            rating: 4.9,
            feature: [.superHost],
            amenities: [.wifi, .pool, .tv,  .balcony],
            type: .villa
        ),
        .init(
            id: UUID().uuidString,
            ownerUId: UUID().uuidString,
            ownerName: "Anjali Nair",
            onwerImageUrl: "https://images.unsplash.com/photo-1505692794403-55b53b8b76b0?auto=format&fit=crop&w=800&q=80",
            numberOfBedrooms: 1,
            numberOfBathroom: 1,
            numberOfGuests: 2,
            numberOfBeds: 1,
            pricePerNight: 1600,
            latitude: 8.5241,
            longitude: 76.9366,
            address: "Backwaters Villa",
            city: "Thiruvananthapuram",
            state: "Kerala",
            title: "Peaceful Stay Near Beach",
            rating: 4.4,
            feature: [],
            amenities: [.wifi,  .laundry],
            type: .villa
        ),
        .init(
            id: UUID().uuidString,
            ownerUId: UUID().uuidString,
            ownerName: "Harshita Jain",
            onwerImageUrl: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80",
            numberOfBedrooms: 3,
            numberOfBathroom: 2,
            numberOfGuests: 5,
            numberOfBeds: 3,
            pricePerNight: 3400,
            latitude: 23.0225,
            longitude: 72.5714,
            address: "SG Highway",
            city: "Ahmedabad",
            state: "Gujarat",
            title: "Modern Apartment with City View",
            rating: 4.6,
            feature: [.selfCheckIn],
            amenities: [.wifi, .kitchen, .tv],
            type: .apartment
        ),
        .init(
            id: UUID().uuidString,
            ownerUId: UUID().uuidString,
            ownerName: "Sahil Khan",
            onwerImageUrl: "https://images.unsplash.com/photo-1600585153837-200f3d3d4edc?auto=format&fit=crop&w=800&q=80",
            numberOfBedrooms: 2,
            numberOfBathroom: 1,
            numberOfGuests: 4,
            numberOfBeds: 2,
            pricePerNight: 2200,
            latitude: 21.1458,
            longitude: 79.0882,
            address: "Dharampeth Road",
            city: "Nagpur",
            state: "Maharashtra",
            title: "Orange City Comfort Stay",
            rating: 4.2,
            feature: [],
            amenities: [.wifi, .tv],
            type: .apartment
        ),
        .init(
            id: UUID().uuidString,
            ownerUId: UUID().uuidString,
            ownerName: "Kavita Desai",
            onwerImageUrl: "https://images.unsplash.com/photo-1560448075-bb0bffddd6dc?auto=format&fit=crop&w=800&q=80",
            numberOfBedrooms: 3,
            numberOfBathroom: 2,
            numberOfGuests: 6,
            numberOfBeds: 3,
            pricePerNight: 3900,
            latitude: 15.2993,
            longitude: 74.1240,
            address: "Baga Beach Road",
            city: "Goa",
            state: "Goa",
            title: "Beachside Getaway",
            rating: 4.8,
            feature: [.selfCheckIn, .superHost],
            amenities: [.wifi, .pool, .balcony, .tv],
            type: .villa
        ),
        .init(
            id: UUID().uuidString,
            ownerUId: UUID().uuidString,
            ownerName: "Rohan Sinha",
            onwerImageUrl: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80",
            numberOfBedrooms: 1,
            numberOfBathroom: 1,
            numberOfGuests: 2,
            numberOfBeds: 1,
            pricePerNight: 2000,
            latitude: 22.5726,
            longitude: 88.3639,
            address: "Park Street",
            city: "Kolkata",
            state: "West Bengal",
            title: "Cosy Heritage Room",
            rating: 4.5,
            feature: [],
            amenities: [.wifi, .kitchen, .laundry],
            type: .apartment
        )
    ]
}


